const CTRYourInformationTypes = {
  CREATE_CTR_YOUR_INFORMATION_START: 'CREATE_CTR_YOUR_INFORMATION_START',
  CREATE_CTR_YOUR_INFORMATION_SUCCESS: 'CREATE_CTR_YOUR_INFORMATION_SUCCESS',
  CREATE_CTR_YOUR_INFORMATION_FAILURE: 'CREATE_CTR_YOUR_INFORMATION_FAILURE',
  RETRIEVE_CTR_YOUR_INFORMATION_START: 'RETRIEVE_CTR_YOUR_INFORMATION_START',
  RETRIEVE_CTR_YOUR_INFORMATION_SUCCESS:
    'RETRIEVE_CTR_YOUR_INFORMATION_SUCCESS',
  RETRIEVE_CTR_YOUR_INFORMATION_FAILURE:
    'RETRIEVE_CTR_YOUR_INFORMATION_FAILURE',
  CREATE_YOUR_INFORMATION_COMMENT_START:
    'CREATE_YOUR_INFORMATION_COMMENT_START',
  CREATE_YOUR_INFORMATION_COMMENT_SUCCESS:
    'CREATE_YOUR_INFORMATION_COMMENT_SUCCESS',
  CREATE_YOUR_INFORMATION_COMMENT_FAILURE:
    'CREATE_YOUR_INFORMATION_COMMENT_FAILURE',
  RETRIEVE_YOUR_INFORMATION_COMMENTS_START:
    'RETRIEVE_YOUR_INFORMATION_COMMENTS_START',
  RETRIEVE_YOUR_INFORMATION_COMMENTS_SUCCESS:
    'RETRIEVE_YOUR_INFORMATION_COMMENTS_SUCCESS',
  RETRIEVE_YOUR_INFORMATION_COMMENTS_FAILURE:
    'RETRIEVE_YOUR_INFORMATION_COMMENTS_FAILURE'
};

export default CTRYourInformationTypes;
