const CTROverviewActionTypes = {
  CREATE_CTR_OVERVIEW_START: 'CREATE_CTR_OVERVIEW_START',
  CREATE_CTR_OVERVIEW_SUCCESS: 'CREATE_CTR_OVERVIEW_SUCCESS',
  CREATE_CTR_OVERVIEW_FAILURE: 'CREATE_CTR_OVERVIEW_FAILURE',
  RETRIEVE_CTR_OVERVIEW_START: 'RETRIEVE_CTR_OVERVIEW_START',
  RETRIEVE_CTR_OVERVIEW_SUCCESS: 'RETRIEVE_CTR_OVERVIEW_SUCCESS',
  RETRIEVE_CTR_OVERVIEW_FAILURE: 'RETRIEVE_CTR_OVERVIEW_FAILURE',
  CREATE_OVERVIEW_COMMENT_START: 'CREATE_OVERVIEW_COMMENT_START',
  CREATE_OVERVIEW_COMMENT_SUCCESS: 'CREATE_OVERVIEW_COMMENT_SUCCESS',
  CREATE_OVERVIEW_COMMENT_FAILURE: 'CREATE_OVERVIEW_COMMENT_FAILURE',
  RETRIEVE_OVERVIEW_COMMENTS_START: 'RETRIEVE_OVERVIEW_COMMENTS_START',
  RETRIEVE_OVERVIEW_COMMENTS_SUCCESS: 'RETRIEVE_OVERVIEW_COMMENTS_SUCCESS',
  RETRIEVE_OVERVIEW_COMMENTS_FAILURE: 'RETRIEVE_OVERVIEW_COMMENTS_FAILURE'
};

export default CTROverviewActionTypes;
