const CTRCommentActionTypes = {
  CREATE_COMMENT_START: 'CREATE_COMMENT_START',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE',
  RETRIEVE_COMMENTS_START: 'RETRIEVE_COMMENTS_START',
  RETRIEVE_COMMENTS_SUCCESS: 'RETRIEVE_COMMENTS_SUCCESS',
  RETRIEVE_COMMENTS_FAILURE: 'RETRIEVE_COMMENTS_FAILURE'
};

export default CTRCommentActionTypes;
