const CTRAuthorSummaryActionTypes = {
  CREATE_CTR_AUTHOR_SUMMARY_START: 'CREATE_CTR_AUTHOR_SUMMARY_START',
  CREATE_CTR_AUTHOR_SUMMARY_SUCCESS: 'CREATE_CTR_AUTHOR_SUMMARY_SUCCESS',
  CREATE_CTR_AUTHOR_SUMMARY_FAILURE: 'CREATE_CTR_AUTHOR_SUMMARY_FAILURE',
  RETRIEVE_CTR_AUTHOR_SUMMARY_START: 'RETRIEVE_CTR_AUTHOR_SUMMARY_START',
  RETRIEVE_CTR_AUTHOR_SUMMARY_SUCCESS: 'RETRIEVE_CTR_AUTHOR_SUMMARY_SUCCESS',
  RETRIEVE_CTR_AUTHOR_SUMMARY_FAILURE: 'RETRIEVE_CTR_AUTHOR_SUMMARY_FAILURE',
  CREATE_AUTHOR_SUMMARY_COMMENT_START: 'CREATE_AUTHOR_SUMMARY_COMMENT_START',
  CREATE_AUTHOR_SUMMARY_COMMENT_SUCCESS:
    'CREATE_AUTHOR_SUMMARY_COMMENT_SUCCESS',
  CREATE_AUTHOR_SUMMARY_COMMENT_FAILURE:
    'CREATE_AUTHOR_SUMMARY_COMMENT_FAILURE',
  RETRIEVE_AUTHOR_SUMMARY_COMMENTS_START:
    'RETRIEVE_AUTHOR_SUMMARY_COMMENTS_START',
  RETRIEVE_AUTHOR_SUMMARY_COMMENTS_SUCCESS:
    'RETRIEVE_AUTHOR_SUMMARY_COMMENTS_SUCCESS',
  RETRIEVE_AUTHOR_SUMMARY_COMMENTS_FAILURE:
    'RETRIEVE_AUTHOR_SUMMARY_COMMENTS_FAILURE'
};

export default CTRAuthorSummaryActionTypes;
