export const diseaseData = [
  'Adrenocortical cancer',
  'Advanced cancer',
  'Advanced cancer/Solid Tumor Only',
  'Advanced cancer/Hematologic Malignancy Only',
  'Anal Cancer',
  'Biliary Tract: Gallbladder Cancer and Chloangiocarcinoma',
  'Bladder Cancer',
  'Brain cancer – primary',
  'Brain cancer – metastatic',
  'Breast cancer',
  'Carcinoid Tumors',
  'Carcinoma of Unknown Primary',
  'Cervical cancer',
  'Colorectal cancer',
  'Endometrial',
  'Esophageal cancer',
  'Gastric cancer',
  'Gestational Trophoblastic Neoplasia',
  'Head and Neck Cancers',
  'Hepatocellular carcinoma',
  'HIV-associated Kaposi’s sarcoma',
  'HIV-associated – other',
  'Kaposi’s sarcoma',
  'Leukemia – acute – ALL (Adult)',
  'Leukemia – acute – AML',
  'Leukemia – chronic - CLL',
  'Leukemia – chronic – CML',
  'Leukemia – Hairy Cell',
  'Lung cancer - NSCLC',
  'Lung cancer – SCLC',
  'Lymphoma – Hodgkin',
  'Lymphoma – Non-Hodgkin',
  'Lymphoma – Other',
  'Melanoma',
  'Mesothelioma',
  'Multiple Myeloma',
  'Neuroendocrine - pancreatic',
  'Neuroendocrine – other',
  'Ovarian cancer',
  'Pancreatic cancer',
  'Pediatric cancer – ALL',
  'Pediatric cancer – Ewing',
  'Pediatric cancer – Neuroblastoma',
  'Pediatric cancer – Osteosarcoma',
  'Pediatric cancer – Rhabdomyosarcoma',
  'Pediatric cancer – Other',
  'Pheochromocytoma Prostate cancer',
  'Renal cell carcinoma – clear cell',
  'Renal cell carcinoma – not clear cell',
  'Sarcomas – Adult',
  'Skin cancer – basal cell carcinoma',
  'Skin cancer – melanoma',
  'Skin cancer – other',
  'Testicular cancer',
  'Thymoma',
  'Thyroid cancer – anaplastic',
  'Thyroid cancer – well differentiated',
  'Thyroid cancer – medullary',
  'Vaginal cancer',
  'Other'
];
