const CTRTrailInformationActionTypes = {
  CREATE_CTR_TRAIL_INFORMATION_START: 'CREATE_CTR_TRAIL_INFORMATION_START',
  CREATE_CTR_TRAIL_INFORMATION_SUCCESS: 'CREATE_CTR_TRAIL_INFORMATION_SUCCESS',
  CREATE_CTR_TRAIL_INFORMATION_FAILURE: 'CREATE_CTR_TRAIL_INFORMATION_FAILURE',
  RETRIEVE_CTR_TRAIL_INFORMATION_START: 'RETRIEVE_CTR_TRAIL_INFORMATION_START',
  RETRIEVE_CTR_TRAIL_INFORMATION_SUCCESS:
    'RETRIEVE_CTR_TRAIL_INFORMATION_SUCCESS',
  RETRIEVE_CTR_TRAIL_INFORMATION_FAILURE:
    'RETRIEVE_CTR_TRAIL_INFORMATION_FAILURE',
  CREATE_TRAIL_INFORMATION_COMMENT_START:
    'CREATE_TRAIL_INFORMATION_COMMENT_START',
  CREATE_TRAIL_INFORMATION_COMMENT_SUCCESS:
    'CREATE_TRAIL_INFORMATION_COMMENT_SUCCESS',
  CREATE_TRAIL_INFORMATION_COMMENT_FAILURE:
    'CREATE_TRAIL_INFORMATION_COMMENT_FAILURE',
  RETRIEVE_TRAIL_INFORMATION_COMMENTS_START:
    'RETRIEVE_TRAIL_INFORMATION_COMMENTS_START',
  RETRIEVE_TRAIL_INFORMATION_COMMENTS_SUCCESS:
    'RETRIEVE_TRAIL_INFORMATION_COMMENTS_SUCCESS',
  RETRIEVE_TRAIL_INFORMATION_COMMENTS_FAILURE:
    'RETRIEVE_TRAIL_INFORMATION_COMMENTS_FAILURE'
};

export default CTRTrailInformationActionTypes;
