const CTRPatientCharacteristicsActionTypes = {
  CREATE_CTR_PATIENT_CHARACTERISTICS_START:
    'CREATE_CTR_PATIENT_CHARACTERISTICS_START',
  CREATE_CTR_PATIENT_CHARACTERISTICS_SUCCESS:
    'CREATE_CTR_PATIENT_CHARACTERISTICS_SUCCESS',
  CREATE_CTR_PATIENT_CHARACTERISTICS_FAILURE:
    'CREATE_CTR_PATIENT_CHARACTERISTICS_FAILURE',
  RETRIEVE_CTR_PATIENT_CHARACTERISTICS_START:
    'RETRIEVE_CTR_PATIENT_CHARACTERISTICS_START',
  RETRIEVE_CTR_PATIENT_CHARACTERISTICS_SUCCESS:
    'RETRIEVE_CTR_PATIENT_CHARACTERISTICS_SUCCESS',
  RETRIEVE_CTR_PATIENT_CHARACTERISTICS_FAILURE:
    'RETRIEVE_CTR_PATIENT_CHARACTERISTICS_FAILURE'
};

export default CTRPatientCharacteristicsActionTypes;
