defaults: &defaults
  options:
    raise_not_found_error: false
development:
  # Configure available database clients. (required)
  clients:
    default:
      database: clinical_trials_development
      hosts:
        - localhost:27017
  <<: *defaults
staging:
  clients:
    default:
      uri: mongodb+srv://admin-user:admin00@alphamed-rewrite.yj9yb.mongodb.net/clinical_trials_development?retryWrites=true&w=majority
  <<: *defaults

production:
  clients:
    default:
      uri: mongodb+srv://admin-user:admin00@alphamed-rewrite.yj9yb.mongodb.net/clinical_trials_development?retryWrites=true&w=majority
  <<: *defaults
