const CTRDrugInformationActionTypes = {
  CREATE_CTR_DRUG_INFORMATION_START: 'CREATE_CTR_DRUG_INFORMATION_START',
  CREATE_CTR_DRUG_INFORMATION_SUCCESS: 'CREATE_CTR_DRUG_INFORMATION_SUCCESS',
  CREATE_CTR_DRUG_INFORMATION_FAILURE: 'CREATE_CTR_DRUG_INFORMATION_FAILURE',
  RETRIEVE_CTR_DRUG_INFORMATION_START: 'RETRIEVE_CTR_DRUG_INFORMATION_START',
  RETRIEVE_CTR_DRUG_INFORMATION_SUCCESS:
    'RETRIEVE_CTR_DRUG_INFORMATION_SUCCESS',
  RETRIEVE_CTR_DRUG_INFORMATION_FAILURE:
    'RETRIEVE_CTR_DRUG_INFORMATION_FAILURE',
  CREATE_DRUG_INFORMATION_COMMENT_START:
    'CREATE_DRUG_INFORMATION_COMMENT_START',
  CREATE_DRUG_INFORMATION_COMMENT_SUCCESS:
    'CREATE_DRUG_INFORMATION_COMMENT_SUCCESS',
  CREATE_DRUG_INFORMATION_COMMENT_FAILURE:
    'CREATE_DRUG_INFORMATION_COMMENT_FAILURE',
  RETRIEVE_DRUG_INFORMATION_COMMENTS_START:
    'RETRIEVE_DRUG_INFORMATION_COMMENTS_START',
  RETRIEVE_DRUG_INFORMATION_COMMENTS_SUCCESS:
    'RETRIEVE_DRUG_INFORMATION_COMMENTS_SUCCESS',
  RETRIEVE_DRUG_INFORMATION_COMMENTS_FAILURE:
    'RETRIEVE_DRUG_INFORMATION_COMMENTS_FAILURE'
};

export default CTRDrugInformationActionTypes;
