const CTRCoAuthorActionTypes = {
  CREATE_CTR_CO_AUTHOR_START: 'CREATE_CTR_CO_AUTHOR_START',
  CREATE_CTR_CO_AUTHOR_SUCCESS: 'CREATE_CTR_CO_AUTHOR_SUCCESS',
  CREATE_CTR_CO_AUTHOR_FAILURE: 'CREATE_CTR_CO_AUTHOR_FAILURE',
  RETRIEVE_CTR_CO_AUTHOR_START: 'RETRIEVE_CTR_CO_AUTHOR_START',
  RETRIEVE_CTR_CO_AUTHOR_SUCCESS: 'RETRIEVE_CTR_CO_AUTHOR_SUCCESS',
  RETRIEVE_CTR_CO_AUTHOR_FAILURE: 'RETRIEVE_CTR_CO_AUTHOR_FAILURE',
  CREATE_CO_AUTHOR_COMMENT_START: 'CREATE_CO_AUTHOR_COMMENT_START',
  CREATE_CO_AUTHOR_COMMENT_SUCCESS: 'CREATE_CO_AUTHOR_COMMENT_SUCCESS',
  CREATE_CO_AUTHOR_COMMENT_FAILURE: 'CREATE_CO_AUTHOR_COMMENT_FAILURE',
  RETRIEVE_CO_AUTHOR_COMMENTS_START: 'RETRIEVE_CO_AUTHOR_COMMENTS_START',
  RETRIEVE_CO_AUTHOR_COMMENTS_SUCCESS: 'RETRIEVE_CO_AUTHOR_COMMENTS_SUCCESS',
  RETRIEVE_CO_AUTHOR_COMMENTS_FAILURE: 'RETRIEVE_CO_AUTHOR_COMMENTS_FAILURE'
};

export default CTRCoAuthorActionTypes;
