export const drug_type =[
    "Antibody",
    "Biological",
    "Immunotoxin",
    "Liposomal encapsulated",
    "Small molecule",
    "Vaccine",
    "Other"
]

export const drug_class = [
    "AKT",
    "ALK",
    "Alkylating agent",
    "Androgen receptor",
    "Antimetabolite",
    "Angiogenesis – VEGF",
    "Angiogenesis",
    "Angiogenesis – antivascular",
    "Anthracycline",
    "Anthracenedione",
    "Apoptosis – Bcl-2",
    "Apoptosis – other",
    "BCR-Abl",
    "c-KIT",
    "Cancer Vaccine",
    "CD20",
    "CD22",
    "CD33",
    "CD52",
    "CD200",
    "CDK",
    "CHK1",
    "CHK2",
    "Demethylating Agent",
    "DNA-PK",
    "Drug Conjugate",
    "EGFR",
    "Estroge receptor",
    "Farnesyl transferase",
    "FLT3",
    "Gene therapy",
    "Geranylgeranyltransferase",
    "HDAC",
    "Her-2/Neu",
    "Hedgehog",
    "HSP90",
    "Insulin-like growth factors – IGF1R and IGF2",
    "Immune therapy",
    "Immunoconjugates",
    "Immunotoxins",
    "JAK kinase",
    "MEK",
    "Mesothelin",
    "MET – cMET",
    "Micro-RNA",
    "Microtubule-targeting agent",
    "Mitotic – Aurora kinase",
    "Mitotic – Kinetic spindle protein",
    "m-TOR",
    "NF-κB pathway",
    "Notch",
    "PAK (p-221 activated kinase)",
    "PARP",
    "PIM kinase",
    "PI3 kinase",
    "PDGFR",
    "Platinum compound",
    "Progesterone receptor",
    "Proteasome",
    "RAD51",
    "Raf – BRAF",
    "Ras",
    "RET",
    "Retinoid",
    "SRC",
    "siRNA",
    "Telomerase",
    "Topoisomerase I",
    "Topoisomerase II",
    "Topoisomerase I /Topoisomerase II",
    "TRAIL pathway",
    "Tubulin/Microtubules targeting agent",
    "Vaccine therapy",
    "VEGF",
    "VEGFR",
    "Vitamin D",
    "WNT/β-catenin pathway",
    "Other"
];

export const drug_unit = [
    "flat dose",
    "kilogram (kg)",
    "squared meter (m2)"
]

export const drug_route = [
    "oral (po)",
    "rectum (pr)",
    "intraperitoneal (IP)",
    "IV, per push",
    "IV",
    "Continuous intravenous infusion (CIV)",
    "Other",
]